### PR TITLE
feat: Refresh models

### LINKED ISSUE #106: Add OpenAI's GPT-4o mini model
Add the latest [GPT-4o mini](https://platform.openai.com/docs/models/gpt-4o-mini) model

### PR DESCRIPTION
**Pull request by esafak**
* Remove old ones, add new ones.
* Update version to 1.9.5

I failed to build and test it because Xcode says the app requires a provisioning profile with the iCloud and Push Notifications features. It seems I need a paid developer profile, am I wrong? I am not familiar with XCode.

Fixes #106 #105

### CODE REVIEW

**Comment by FliiFe** [comment]
You only need a paid account to publish, you should be able to run without one by changing the provisioning profile in the app's settings.

I'll check this out but this probably doesn't compile, updating models involves adding a pricing scheme too. I'll try to merge this soon

**Comment by FliiFe** [comment]
I'll merge if you include the following patch

```patch
diff --git a/Machato/Data/DataTypes/APICost.swift b/Machato/Data/DataTypes/APICost.swift
index 67d4eed..9977d9e 100644
--- a/Machato/Data/DataTypes/APICost.swift
+++ b/Machato/Data/DataTypes/APICost.swift
@@ -14,40 +14,35 @@ struct ModelCost {
     
     static let gpt3 : ModelCost = .init(sent: 0.0005, received: 0.0015)
     static let gpt4 : ModelCost = .init(sent: 0.03, received: 0.06)
-    static let gpt4_32k : ModelCost = .init(sent: 0.06, received: 0.12)
     static let gpt4_turbo : ModelCost = .init(sent: 0.01, received: 0.03)
     static let gpt4_o : ModelCost = .init(sent: 0.005, received: 0.015)
-    
+    static let gpt4_o_20240806 : ModelCost = .init(sent: 0.0025, received: 0.010)
+    static let gpt_4o_mini : ModelCost = .init(sent: 0.00015, received: 0.0006)
+
     static func getOpenAIModelCost(model: String) -> ModelCost {
         switch OpenAIChatModel.fromString(model) {
         case .gpt_35_turbo:
             return gpt3
         case .gpt_4:
             return gpt4
-        case .gpt_4_32k:
-            return gpt4_32k
         case .gpt_4_turbo:
             return gpt4_turbo
-        case .gpt_4_turbo_preview:
-            return gpt4_turbo
-        case .gpt_4_turbo_vision:
-            return gpt4_turbo
         case .gpt_4o:
             return gpt4_o
+        case .gpt_4o_20240806:
+            return gpt4_o_20240806
+        case .gpt_4o_mini:
+            return gpt_4o_mini
         }
     }
     
     static func getAnthropicModelCost(model : String) -> ModelCost {
         switch AnthropicModel.fromString(model) {
-        case .claude_instant_v1:
-            return .init(sent: 0.8 / 1_000, received: 2.4 / 1_000)
-        case .claude_v2, .claude_v2_1:
-            return .init(sent: 8.0 / 1_000, received: 24.0 / 1_000)
-        case .claude_haiku:
+        case .claude_3_haiku:
             return .init(sent: 0.25 / 1_000, received: 1.25 / 1_000)
-        case .claude_sonnet:
+        case .claude_3_sonnet, .claude_35_sonnet:
             return .init(sent: 3.0 / 1_000, received: 15.0 / 1_000)
-        case .claude_opus:
+        case .claude_3_opus:
             return .init(sent: 15.0 / 1_000, received: 75.0 / 1_000)
         }
     }
diff --git a/Machato/Data/DataTypes/Models/AnthropicModel.swift b/Machato/Data/DataTypes/Models/AnthropicModel.swift
index 8dc1d78..569800d 100644
--- a/Machato/Data/DataTypes/Models/AnthropicModel.swift
+++ b/Machato/Data/DataTypes/Models/AnthropicModel.swift
@@ -25,7 +25,7 @@ enum AnthropicModel: String, CaseIterable, Identifiable, ModelEnum {
     }
     
     var id : String { return self.rawValue }
-    static let default_case : Self = .claude_haiku
+    static let default_case : Self = .claude_3_haiku
     static func fromString(_ sm: String?) -> Self {
         guard let s = sm else { return default_case }
         for c in Self.allCases {
```

Save it as a file and use `patch` on the command line to apply it.

**Comment by tjbcg** [comment]
Thank you for contributing ;-)
I'll publish a new version/binary soon

**Comment by esafak** [comment]
I look forward to the new release.

**Pull request merged**
